SET ESCAPE OFF
SET MULTILOCKS ON
SET TALK OFF
SET NOTIFY CURSOR OFF
SET SAFETY OFF
*SET SYSMENU OFF

SET PROCEDURE TO 
SET PROCEDURE TO sampletextbox.prg ADDITIVE

LOCAL loWMCP
loWMCP = NEWOBJECT("wm_command_proc", "wm_command_proc.prg")

DO FORM sample

READ EVENTS

loWMCP.Release()

SET SYSMENU ON

